---
abstract: 'Stalk a HTTP URI efficiently and invoke code when it changes'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-HTTP-Monitor
provides:
  Net::Async::HTTP::Monitor:
    file: lib/Net/Async/HTTP/Monitor.pm
    version: '0.001000'
requires:
  Carp: '0'
  Class::Tiny: '0'
  IO::Async::Timer::Periodic: '0'
  perl: '5.006'
  strict: '0'
  subs: '0'
  warnings: '0'
version: '0.001000'
